version: '3.1'
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    hostname: 127.0.0.1
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto:/mosquitto/config
    networks:
      - webnet

networks:
  webnet:
